# Generated by Django 4.1.5 on 2023-02-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='No category', max_length=30)),
                ('category_name', models.CharField(default='No category', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
