# Generated by Django 4.1.5 on 2023-02-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productcategory_remove_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_id',
            field=models.CharField(default='No category id', max_length=30),
        ),
    ]
