# Generated by Django 4.1.5 on 2023-01-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField()),
                ('title', models.TextField()),
                ('old_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('href', models.TextField()),
                ('brand', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
