# Generated by Django 4.1.5 on 2023-01-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_brand_product_category_product_current_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsInputField',
            new_name='InputField',
        ),
    ]
