# Generated by Django 4.1.5 on 2023-01-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_productsinputfield_inputfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputField',
            new_name='ProductList',
        ),
    ]
